backend:
  name: github
  repo: COMOESTAELTIEMPOENTUESCUELA/Estacionesmeteorologicas # Usa tu usuario/repo
  branch: main 

# Rutas de Archivos
media_folder: "imagenes/reportes" 
public_folder: "imagenes/reportes" # <<-- CORREGIDO: SE QUITÓ LA BARRA INCLINADA INICIAL

collections:
  - name: "reportes"
    label: "Talleres y Reportes" 
    folder: "_data/reportes" 
    create: true 
    slug: "{{title}}-{{month}}-{{day}}"
    fields:
      - {label: "Título del Reporte", name: "title", widget: "string", required: true}
      - {label: "Fecha de Publicación", name: "date", widget: "date", required: true, format: "DD/MM/YYYY"}
      - {label: "Descripción Corta", name: "summary", widget: "text", required: true, hint: "Máximo 2-3 frases"}
      - {label: "Escuela Involucrada", name: "school", widget: "string"}
      - {label: "Foto Principal", name: "image", widget: "image", required: true}
      - {label: "Contenido Completo (Opcional)", name: "body", widget: "markdown", required: false, hint: "Aquí pueden escribir el reporte completo si es necesario."}
